apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: locust-ingress
spec:
  rules:
    - host: locust.storm200825.tk
      http:
        paths:
          - backend:
              serviceName: http-file-test-1-http-v8
              servicePort: 3030