{
 "title": "Twitter Analytics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Top 10 Lang",
   "type": "graph",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(10, sum(language_total) by (lang)))",
     "legendFormat": "{{lang}}"
    }
   ]
  },
  {
   "title": "Hastags",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 22, "w": 9, "x": 15, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(topk(50, sum(hashtags_total) by (htag)))",
     "legendFormat": "{{htag}}"
    }
   ]
  },
  {
   "title": "Total Tweets",
   "type": "graph",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(message_hashtags_total)", "legendFormat": "Running Count" }
   ]
  }
 ]
}