apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  # name: paradymelabs-ca-issuer
  name: letsencrypt-staging
  #name: letsencrypt-production
spec:
  acme:
    email: luther.mcginty@paradyme.us
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    #server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      # name: paradymelabs-ca-issuer
      name: letsencrypt-staging
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
      - http01:
          ingress:
            class: nginx